<a href="https://colab.research.google.com/github/bharathkumaarr/Machine-Learning/blob/main/Python-Libraries/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy - Numerical Python


Advantages:
1. Allows several mathematical Operations
2. Faster operations

Library(Pre-made functions/classes)

In [1]:
import numpy as np

Time Taken by List & Numpy

In [2]:
from time import process_time

*time taken by a list*

In [3]:
python_list = [i for i in range(10000000)]
start_time = process_time()
python_list = [i+5 for i in python_list ]
end_time = process_time()
print(end_time - start_time)

0.7426290099999999


*time taken by Numpy*

In [4]:
np_array = np.array([i for i in range(10000000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.010413956000000724


#Numpy Arrays

In [5]:
list1 = [1,2,3,4,5]
print(type(list1))
print(list1)

<class 'list'>
[1, 2, 3, 4, 5]


In [6]:
np_array = np.array(list1)
print(type(np_array))
print(np_array)

<class 'numpy.ndarray'>
[1 2 3 4 5]


ndarray: N-Dimensional array

Similar to a Matrix

In [7]:
#creating a 1 Dimensional Array
a = np.array([123,345,67,89])
print(a)

[123 345  67  89]


In [8]:
print(a)
a.shape #gives number of columns and rows
# for 1d array first number is number of columns

[123 345  67  89]


(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,77,8)])
print(b)
b.shape #gives number of rows and columns (rows and columns)

[[ 1  2  3  4]
 [ 5  6 77  8]]


(2, 4)

In [10]:
c = np.array([(1,2,3,4), (5,6,7,8)],dtype = float) #default is int
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = str)
print(c)

[['1' '2' '3' '4']
 ['5' '6' '7' '8']]


Initial Place Holder in numpy arrays

In [12]:
#create a numpy array of zeros
x = np.zeros((4,5)) # 4 rows and 5 columns
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create a numpy array of ones
y = np.ones((3,4)) # 3 rows and 4 columns
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#create a numpy array of specific values
z = np.full((4,5),3) # 4 rows and 5 columns
print(z)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [15]:
#create identity matrix
i = np.eye(4) #4x4 matrix
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#create numpy array with random values
n = np.random.random((3,4))
print(n) # all numbers between 0 and 1

[[0.26596526 0.39691545 0.71451783 0.69443735]
 [0.97354225 0.9464284  0.07400786 0.69276807]
 [0.39458343 0.45637605 0.41931551 0.65206105]]


In [17]:
# random integer values array with specific range
n = np.random.randint(10,100,(3,5)) #10 to 100
print(n)

[[24 11 30 90 32]
 [14 69 36 95 75]
 [66 33 49 25 55]]


In [18]:
#array of evenly spaced values ---> specifying number of values we want betwen the range
a = np.linspace(10,30,5)
print(a)

[10. 15. 20. 25. 30.]


In [19]:
#array of evenly spaced values ---> specifying the step
b = np.arange(10,30,5) # a-range
print(b)

[10 15 20 25]


In [20]:
#convert a list/tuple to numpy array
list2 = [1,2,4,5,6,7,7] # (1,2,3,4,5,6)
nparray = np.asarray(list2)
print(nparray)
print(type(nparray))

[1 2 4 5 6 7 7]
<class 'numpy.ndarray'>


#Analysing Numpy Arrays

In [21]:
new = np.random.randint(10,100,(5,5)) #10 to 100
print(new)

[[19 17 30 54 54]
 [95 13 83 42 12]
 [40 99 74 96 13]
 [35 44 21 49 91]
 [25 27 30 90 26]]


In [22]:
#array dimension
print(new.shape)

(5, 5)


In [23]:
#number of dimensions
print(new.ndim)

2


In [24]:
#number of elements
print(new.size)

25


In [25]:
#to check datatpe of values
print(new.dtype)

int64


#Mathematical Operations on MumPy array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #concatenate

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 0 5]
 [9 2 7]
 [5 3 1]]
[[13 19 11]
 [14 13 18]
 [14 11 13]]


In [28]:
print(a+b) #element wise addition like in matrices

[[15 19 16]
 [23 15 25]
 [19 14 14]]


In [29]:
print(a*b)

[[ 26   0  55]
 [126  26 126]
 [ 70  33  13]]


In [30]:
print(np.add(a,b)) # same as a+b

[[15 19 16]
 [23 15 25]
 [19 14 14]]


In [31]:
print(np.subtract(a,b))

[[-11 -19  -6]
 [ -5 -11 -11]
 [ -9  -8 -12]]


In [32]:
print(np.multiply(a,b))

[[ 26   0  55]
 [126  26 126]
 [ 70  33  13]]


In [33]:
print(np.divide(a,b))

[[0.15384615 0.         0.45454545]
 [0.64285714 0.15384615 0.38888889]
 [0.35714286 0.27272727 0.07692308]]


#Array Manuipulation

In [34]:
array1 = np.random.randint(0,100,(2,3))
print(array1)
print(array1.shape)

[[95 47  2]
 [78 29 68]]
(2, 3)


In [35]:
#transpose
trans = np.transpose(array1)
print(trans)
print(trans.shape)

[[95 78]
 [47 29]
 [ 2 68]]
(3, 2)


In [36]:
#another method to find transpose
trans2 = array1.T
print(trans2)
print(trans2.shape)

[[95 78]
 [47 29]
 [ 2 68]]
(3, 2)


In [37]:
#reshaping array
p = np.random.randint(0,100,(3,4))
print(p)
print(p.shape)

[[54  1 81 20]
 [30 13 59 88]
 [87 63 42 79]]
(3, 4)


In [38]:
q = p.reshape(4,3)
print(q)
print(q.shape)

[[54  1 81]
 [20 30 13]
 [59 88 87]
 [63 42 79]]
(4, 3)
